### ISSUE TITLE
hierarchical argument with default selected is not working

### ISSUE THREAD

**Issue by msgoussi** [dreamRs/shinytreeview#1]
library(shiny)
library(shinytreeview)
library(shinyWidgets)
library(dplyr)

x <- mutate(cities, all = "All")

ui <- fluidPage(
  tags$h3("treeviewInput cities example"),
# convert to combo box list
  dropdownButton(circle = FALSE, label = "Show Tree", 
  treecheckInput(
    inputId = "tree",
    label = NULL,
# is not selecting all levels below it
    selected = "All", 
    choices = make_tree(
      x, c("all", "continent", "country", "city")
    ),
    borders = FALSE, 
    width = "100%"
  ) 
  ) 
,
  verbatimTextOutput(outputId = "result")
)

server <- function(input, output, session) {
  output$result <- renderPrint({
    input$tree
  })
}

if (interactive())
  shinyApp(ui, server)

**Comment by pvictor** [comment]
Hello,
Thanks for reporting, it works now.

Victor
