### ISSUE TITLE
Make parent nodes un-selectable

### ISSUE THREAD

**Issue by philiph99** [dreamRs/shinytreeview#11]
I want to avoid that users can select parent nodes as input. 

Is there a way to make parent nodes (i.e., continent or country in the cities dataset) un-selectable?

**Comment by razz-matazz** [comment]
This is possible: 
change ```make_tree``` to ```make_tree(cities, c("continent", "country", "city"), continent = list(selectable = FALSE))```

@pvictor If i don't know the name of the first column (because user can upload any table), it's not possible to use this, as ```continent``` is "hardcoded" here, isn't it?

**Comment by philiph99** [comment]
I adapted the cities example, however, "continent" is still selectable after including continent = list(selectable = FALSE):
`
library(shiny)
library(shinytreeview)

ui <- fluidPage(
  treeviewInput(
    inputId = "tree1",
    label = "Choose an area:",
    choices = make_tree(cities, c("continent", "country", "city")),
    continent = list(selectable = FALSE)
),
textOutput("tree1_selected")

)

server <- function(input, output){ 
  output$tree1_selected <- renderText(
    print(input$tree1)
    )
 
  }

shinyApp(ui, server)`

I am using version: shinytreeview_0.1.3

**Comment by pvictor** [comment]
@razz-matazz that's indeed the right way

@philiph99 `continent = list(selectable = FALSE)` must be an argument of `make_tree()` not `treeviewInput()`, e.g. : 

```r
library(shiny)
library(shinytreeview)

ui <- fluidPage(
  treeviewInput(
    inputId = "tree1",
    label = "Choose an area:",
    choices = make_tree(
      data = cities, 
      levels = c("continent", "country", "city"),
      continent = list(selectable = FALSE)
    )
  ),
  textOutput("tree1_selected")
  
)

server <- function(input, output){
  output$tree1_selected <- renderText(
    print(input$tree1)
  )
  
}

shinyApp(ui, server)
```

@razz-matazz to do this programmatically you have to construct the call, you can do this with {rlang} or even base R : 

```r
args <- list(
  data = cities, 
  levels = c("continent", "country", "city")
)
args[names(cities)[1:2]] <- list(list(selectable = FALSE))
do.call(make_tree, args) # use this in treeviewInput(choices = )
```
Like this, first two levels won't be selectable

**Comment by razz-matazz** [comment]
Thanks, that helped a lot.

**Comment by philiph99** [comment]
I now experienced another issue and created a reproducible example (see below) using the cities dataset. 

After making the first two nodes (continent & country) unselectable, they are now still selected and in the app, I can not unselect them.

What can I do so that in the example below, again only the cities are selectable?

Thank you in advance!

```
library(shiny)
library(shinytreeview)

my_cities <- rbind(
  shinytreeview::cities, 
  data.frame(continent = "Luxemburg", 
             country = "Luxemburg",
             city = "Luxemburg")
)

args <- list(
  data = my_cities, 
  levels = c("continent", "country", "city")
)

args[names(my_cities)[1:2]] <- list(list(selectable = FALSE))
tree <- do.call(make_tree, args)

ui <- fluidPage(
  treeviewInput(inputId = "tree", label = "Tree", 
                choices = tree, selected = "Luxemburg", 
                multiple = T),
  verbatimTextOutput("tree_output")
)

server <- function(input, output, session) {
  
  output$tree_output <- renderText({
    input$tree
  })
  
}

shinyApp(ui, server)
```
