### ISSUE TITLE
plus/minus icons missing?

### ISSUE THREAD

**Issue by razz-matazz** [dreamRs/shinytreeview#13]
Hello,

It's just now that I realized that my shinytreeviews (when using your examples) miss something your screenshots show: the "plus" (resp. "minus") in front of the lines that indicate whether this line is open or closed. 

Is this intended?

**Comment by pvictor** [comment]
Indeed, thanks for reporting. This was caused by last [phosphoricons](https://github.com/dreamRs/phosphoricons) release, re-install shinytreeview from GitHub and it'll be fixed.

Victor
