### ISSUE TITLE
Order of variables

### ISSUE THREAD

**Issue by food-data-sci** [dreamRs/shinytreeview#2]
Is there any way in which I can control the order in which the levels appears in treecheckInput in my app? E.g. in the example you show with continent -> country -> city, the continents appear in this order: America, Africa, Europe, Antarctica.
 How is it currently determined? In my app 'Other' comes first which is unfortunate and I would like to change it.

also, is there an equivalent of searchtreeview for treecheckInput?

**Comment by pvictor** [comment]
Hello,

This should be the order in your data:

```r
ex1 <- make_tree(cities, c("continent", "country", "city"))
str(ex1, max.level = 2)
# List of 4
#   $ :List of 2
#   ..$ text : chr "America"
#   ..$ nodes:List of 2
#   $ :List of 2
#   ..$ text : chr "Africa"
#   ..$ nodes:List of 2
#   $ :List of 2
#   ..$ text : chr "Europe"
#   ..$ nodes:List of 3
#   $ :List of 2
#   ..$ text : chr "Antarctica"
#   ..$ nodes: list()
ex2 <- make_tree(cities[order(cities$city), ], c("continent", "country", "city"))
str(ex2, max.level = 2)
# List of 4
#   $ :List of 2
#   ..$ text : chr "Africa"
#   ..$ nodes:List of 2
#   $ :List of 2
#   ..$ text : chr "Europe"
#   ..$ nodes:List of 3
#   $ :List of 2
#   ..$ text : chr "America"
#   ..$ nodes:List of 2
#   $ :List of 2
#   ..$ text : chr "Antarctica"
#   ..$ nodes: list()
```

`searchTreeview()` is badly named, it should work with `treecheckInput()`.

Victor

**Comment by food-data-sci** [comment]
Thanks! Is there a way to stop the tree from expanding before any value is typed into the search?
